spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: SERVICE-SYSTEM
  application:
    name: SERVICE-SYSTEM
  datasource:
    url: jdbc:postgresql://localhost:5432/SADM_SYSTEM
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8081
